[package]
org = "mosip"
name = "consolidatorService"
version = "1.2.0"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]] 
path = "./javalibs/kafka-admin-client-1.0.0.jar"
modules = ["inittopic"]