name: Ballerina Build and push 

on:
  push:
    branches:
      - develop
      - 1.*
      - websub_scalling
      - kafkahub
  workflow_dispatch:
  
jobs:
  build-websub-server:
    runs-on: ubuntu-latest
    env: 
      NAMESPACE: ${{ secrets. dev_namespace_docker_hub }}
      SERVICE_NAME: websub-service
      CONSOLIDATOR_SERVICE_NAME: consolidator-websub-service
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: AdoptOpenJDK/install-jdk@v1
        with: 
          version: '11'
          
      - name: Setup branch and env 
        run: |
         # Strip git ref prefix from version
         echo "BRANCH_NAME=$(echo ${{ github.ref }} | sed -e 's,.*/\(.*\),\1,')" >> $GITHUB_ENV
         echo "GPG_TTY=$(tty)" >> $GITHUB_ENV
         echo $JAVA_HOME
         
      - name: Install ballerina
        run: |
         wget -q --show-progress https://dist.ballerina.io/downloads/swan-lake-beta2/ballerina-linux-installer-x64-swan-lake-beta2.deb -O ballerina-linux-installer-x64.deb
         sudo dpkg -i ballerina-linux-installer-x64.deb
      
      - name: Hub-service build
        run: |
         bal build ./hub 

      #- name: Consolidator service build
      #  run: |
      #   bal build ./consolidator
         
      - name: Build hub image
        run: |
          docker build ./hub --file ./hub/Dockerfile --tag ${{ env.SERVICE_NAME }}
      
    #  - name: Build consolidator image
    #    run: |
    #      docker build ./consolidator --file ./consolidator/Dockerfile --tag ${{ env.CONSOLIDATOR_SERVICE_NAME }}    

      - name: Log into registry
        run: echo "${{ secrets.release_docker_hub }}" | docker login -u ${{ secrets.actor_docker_hub }} --password-stdin
        
      - name: Push images
        run: |
          HUB_IMAGE_ID=$NAMESPACE/$SERVICE_NAME
          
          # Change all uppercase to lowercase
          HUB_IMAGE_ID=$(echo $HUB_IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=$BRANCH_NAME
          echo "push version $VERSION"
          echo HUB_IMAGE_ID=$HUB_IMAGE_ID
          echo VERSION=$VERSION
          docker tag $SERVICE_NAME $HUB_IMAGE_ID:$VERSION
          docker push $HUB_IMAGE_ID:$VERSION